services:
  - type: web
    name: arqia-backend
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: python manage.py migrate --noinput --settings=arqia.settings.prod && gunicorn arqia.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --timeout 400 --access-logfile - --error-logfile - --log-level info
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: arqia.settings.prod
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: arqia_adv7
          property: connectionString
      - key: ALLOWED_HOSTS
        value: .onrender.com
